#!/bin/bash -l
#SBATCH -J run_cnn_test
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=8G
#SBATCH -t 24:00:00
#SBATCH -A UMIC0060
#SBATCH -p dav
#SBATCH -e run_cnn_test.err.%J
#SBATCH -o run_cnn_test.out.%J
#SBATCH -C v100

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

source ~/.bashrc
srun ../scripts/run_cnn.py /glade/scratch/cjablono/fv091x180L26_moist_HS/ ../results/cnn/ -training_features fv091x180L26_moist_HS.cam.h0.2000-12-27-00000.nc -testing_features fv091x180L26_moist_HS.cam.h0.2001-01-11-00000.nc --epochs 16
